[build]
base = "sellary-frontend"
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "20"
NEXT_PUBLIC_API_URL = "/api"
NEXT_PUBLIC_API_PROXY_TARGET = "https://sellary-production-30ec.up.railway.app"

[[plugins]]
package = "@netlify/plugin-nextjs"
