"""remove_restaurant_and_offline_fields

Revision ID: d6220dc5b3cb
Revises: 0e71611c222d
Create Date: 2026-05-26 11:02:55.140173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6220dc5b3cb'
down_revision: Union[str, None] = '0e71611c222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    op.drop_index(op.f('ix_sales_context_type'), table_name='sales')
    op.drop_column('sales', 'context_type')
    op.drop_column('sales', 'table_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('context_type', postgresql.ENUM('retail', 'restaurant', name='salecontexttype'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sales_context_type'), 'sales', ['context_type'], unique=False)
    op.add_column('products', sa.Column('product_type', postgresql.ENUM('item', 'dish', name='producttype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
