// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/login" | "/owner" | "/owner/login" | "/pos" | "/products" | "/purchase-orders" | "/reports" | "/restaurant" | "/restaurant/order" | "/restaurant/orders" | "/restaurant/orders/[saleId]" | "/restaurant/payment/[tableName]" | "/restaurant/table/[tableName]" | "/sales" | "/settings" | "/suppliers" | "/~offline"
type PageRoutes = never
type LayoutRoutes = "/" | "/owner" | "/restaurant"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/~offline": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/dashboard": {}
  "/login": {}
  "/owner": {}
  "/owner/login": {}
  "/pos": {}
  "/products": {}
  "/purchase-orders": {}
  "/reports": {}
  "/restaurant": {}
  "/restaurant/order": {}
  "/restaurant/orders": {}
  "/restaurant/orders/[saleId]": { "saleId": string; }
  "/restaurant/payment/[tableName]": { "tableName": string; }
  "/restaurant/table/[tableName]": { "tableName": string; }
  "/sales": {}
  "/settings": {}
  "/suppliers": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/owner": never
  "/restaurant": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
