// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(protected)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/order">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/orders/[saleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/orders/[saleId]">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/orders/[saleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/payment/[tableName]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/payment/[tableName]">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/payment/[tableName]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/table/[tableName]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/table/[tableName]">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/table/[tableName]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/(protected)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../src/app/owner/(protected)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/login">> = Specific
  const handler = {} as typeof import("../../src/app/owner/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/~offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/~offline">> = Specific
  const handler = {} as typeof import("../../src/app/~offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/restaurant/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/restaurant">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/restaurant/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../src/app/owner/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
